//actual files, folders will be stored in the cloudinary, mongodb will store only the metadata
//metadata like file name, filetype, size, cloudinary link, who owns it, which folder it is in, is it deleted or not

import mongoose from "mongoose";

const fileSchema = new mongoose.Schema({
    //original file name
    name: {
        type: String,
        required: [true, 'File name is required'],
        trim: true
    },
    // File type — image, video, pdf, document etc
    type: {
        type: String,
        required: [true, 'File type is required']
    },
    size: {
        type: Number,
        required: [true, 'File Size is required']
    },
    // Cloudinary secure URL to access the file
    url: {
        type: String,
        required: [true, 'File url is required']
    },
    // Cloudinary public ID — needed to delete file from cloudinary
    cloudinaryId: {
        type: String,
        required: [true, 'Cloudinary ID is required']
    },
    ownerId: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'User',
        required: [true, 'Owner is required']
    },
    // Which folder this file belongs to
    // null means it is in root (My Drive)
    folderId: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'Folder',
        default: null
    },
    // Soft delete — file moves to trash
    // We never immediately delete from DB
    isDeleted: {
        type: Boolean,
        default: false
    },
    //when file was moved to trash
    deletedAt: {
        type: Date,
        default: null
    },
    // Thumbnail URL generated by Cloudinary
    // For images and videos
    thumbnailUrl: {
        type: String,
        default: null
    },
    // Has virus scan been completed
    isScanned: {
        type: Boolean,
        default: false
    },
    // Did virus scan find anything
    isSafe: {
        type: Boolean,
        default: true
    },
     // Is file starred by owner
  isStarred: {
    type: Boolean,
    default: false
  }
},{ timestamps: true })

// Indexes for faster queries
// We frequently search files by owner and folder
// Indexes make these queries much faster

fileSchema.index({ ownerId: 1 })
fileSchema.index({ folderId: 1 })
fileSchema.index({ isDeleted: 1 })

const File = mongoose.model('File', fileSchema)
export default File